public class EmplyeeDetails
{
  Public integer emcode,age ;
  Public string empName,address, Id,desigination;
  Public date Joinigdate;
  Public  Decimal Salaryamount;
  Public Boolean isactive;
     
}

// Manage the prouduct details.
/*Public class ProductDetails
{
    Public integer Productcode,Quantity;
    Public string ProductName, Manufacturer;
    Public Date Expiredate;
    Public Decimal Unitprice;
    Public Boolean isinstock;
}*/