public class MathOperationUtility 
{
    Public static void Addition(integer x, integer y,integer z)
    {
        system.debug('Addition Result:'+(x+y+z));
    }
    public static void Multiply(integer x,integer y)
    {
        system.debug('Multiply result is..:'+(x*y));
    }
    public static void Division(integer x, integer y)
    {
        system.debug('Division result is :'+ (x/y));
    }
}